# Generated by Django 4.2.11 on 2025-04-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_area_code_alter_area_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodule',
            name='short_name',
        ),
    ]
