# Generated by Django 4.2.11 on 2025-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_email_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_company',
            field=models.CharField(max_length=255),
        ),
    ]
