# Generated by Django 4.2.11 on 2025-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_company_email_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_company',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
