# Generated by Django 4.2.11 on 2025-04-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_email_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email_company',
        ),
    ]
