# Generated by Django 4.2.11 on 2025-05-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_company_email_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('mods', models.CharField(blank=True, max_length=255, null=True)),
                ('cats', models.CharField(blank=True, max_length=255, null=True)),
                ('itemsID', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
