# Generated by Django 4.2.11 on 2025-05-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_system',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
