# Generated by Django 4.2.11 on 2025-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification_system_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_system',
            name='status',
            field=models.CharField(blank=True, default='create', max_length=255, null=True),
        ),
    ]
