# Generated by Django 4.2.11 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notification_system_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='accept_terms_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
