version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: /home/ubuntu/test-sia/scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/test-sia/scripts/run_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /home/ubuntu/test-sia/scripts/stop_app.sh
      runas: root
      timeout: 10