version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: scripts/run_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root