version: 0.0
os: linux
hooks:
  BeforeInstall:
    - commands: cd /home/ubuntu/test-sia
      location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - commands: cd /home/ubuntu/test-sia
      location: scripts/run_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - commands: cd /home/ubuntu/test-sia
      location: scripts/stop_app.sh
      runas: root
      timeout: 10