version: 0.0
os: linux
files:
  - destination: /home/ubuntu/test-sia
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      runas: root
      timeout: 300