services:
  db:
    container_name: database
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./venv/postgres.env 
    networks:
      - dbnet

  sia-app:
    container_name: sia-app-test
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./docs/:/app/docs/
      - ./staticfiles/:/app/staticfiles/
      - ./users/migrations/:/app/users/migrations
      - ./modules/:/app/modules
#     - ../pwa/:/manifest.json
#     - ../pwa/service-worker.js:/service-worker.js
    networks:
      - nginxnet
      - dbnet
    depends_on:
      - db

  sia-nginx:
    container_name: sia-nginx-test
    image: nginx
    ports:
      - "80:80"
    #  - "443:443"
    volumes:
      - ./nginx-local/local.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/staticfiles/
    #  - ./certbot/letsencrypt:/etc/letsencrypt/:ro
    #  - ./certbot/www:/var/www/certbot/:ro
      - ./manifest.json:/manifest.json
      - ./service-worker.js:/service-worker.js
      - ./modules/:/app/modules/
      - ./modules/templates/:/var/www/html/
    networks:
      - nginxnet
    depends_on:
      - sia-app

networks:
  nginxnet:
    driver: bridge
  certnet:
    driver: bridge
  dbnet:
    driver: bridge