services:
  db:
    container_name: sia-database
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./venv/postgres.env 
    networks:
      - dbnet

  sia-app:
    container_name: sia-app-test
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./docs/:/app/docs/
      - ./staticfiles/:/app/staticfiles/
      - ./users/migrations/:/app/users/migrations
      - ./modules/:/app/modules
      - ./core/:/app/core/
      - ./templates/:/app/templates/
#     - ../pwa/:/manifest.json
#     - ../pwa/service-worker.js:/service-worker.js
    networks:
      - nginxnet
      - dbnet
    depends_on:
      - db

  sia-nginx:
    container_name: sia-nginx-test
    image: nginx
    ports:
      - "80:80"
    #  - "443:443"
    volumes:
      - ./nginx-local/local.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/staticfiles/
    #  - ./certbot/letsencrypt:/etc/letsencrypt/:ro
    #  - ./certbot/www:/var/www/certbot/:ro
    #  - ./manifest.json:/manifest.json
    #  - ./service-worker.js:/service-worker.js
      - ./modules/:/app/modules/
      - ./modules/templates/:/var/www/html/
    networks:
      - nginxnet
    depends_on:
      - sia-app

  sia-celery:
    build: .
    command: celery -A core.celery worker --pool=solo -l info
    environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://sia-redis:6379/0
    volumes:
      - .:/SIA
    depends_on:
      - sia-redis
      - db
      - sia-app
    networks:
        - dbnet
        - app_network

  sia-celery-beat:
    build: .
    command: celery -A  core beat -l info
    environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://sia-redis:6379/0
    volumes:
      - .:/SIA
    depends_on:
      - sia-redis
      - db
      - sia-celery
    networks:
      - dbnet
      - app_network

  sia-redis:
      image: "redis:alpine"
      container_name: sia-redis
      ports:
        - "6379:6379"  # Habilitar el puerto 6379
      networks:
        - app_network

networks:
  nginxnet:
    driver: bridge
  certnet:
    driver: bridge
  dbnet:
    driver: bridge
  app_network:
    driver: bridge