services:

#  db:
#    container_name: database
#    image: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - ./venv/postgres.env 
#    networks:
#      - dbnet

  sia-git:
    container_name: sia-git
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./docs/:/app/docs/
      - ./staticfiles/:/app/staticfiles/
      - ./users/migrations/:/app/users/migrations
      - ./modules/migrations:/app/modules/migrations
#      - ../pwa/:/manifest.json
#      - ../pwa/service-worker.js:/service-worker.js
    networks:
      - nginxnet
      - jenkins_network
#      - dbnet
#    depends_on:
#      - db

  nginx:
    container_name: nginx-sia
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sia.conf:/etc/nginx/conf.d/default.conf:rw
      - ./staticfiles/:/staticfiles/
      - ./modules/templates/:/var/www/html/
      - ./certbot/letsencrypt:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./manifest.json:/manifest.json
      - ./service-worker.js:/service-worker.js
    networks:
      - nginxnet
      - certnet
      - jenkins_network
    depends_on:
      - sia-git

  certbot:
    container_name: sia-certbot
    image: certbot/certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
#      - ./servers-data/certbot/log:/var/log
    networks:
      - certnet
      - jenkins_network

networks:
  nginxnet:
    driver: bridge
  certnet:
    driver: bridge
  jenkins_network:
    external: true
#  dbnet:
#    driver: bridge