# Generated by Django 4.2.11 on 2024-08-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Corto')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
