# Generated by Django 4.2.11 on 2024-08-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_equipment_tools_responsiva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment_Tools_Responsiva',
        ),
    ]
