# Generated by Django 4.2.11 on 2024-08-15 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0005_delete_equipment_tools_responsiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Tools_Responsiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Cantidad')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('times_requested_responsiva', models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Tiempo solicitado')),
                ('conditions', models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Condiciones')),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='modules.equipment_tools', verbose_name='Equipo')),
                ('responsible_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable temporal')),
            ],
        ),
    ]
