# Generated by Django 4.2.11 on 2024-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_equipment_tools_responsiva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment_tools_responsiva',
            old_name='conditions',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='document_equipment',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='status_equipment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado del Equipo'),
        ),
    ]
