# Generated by Django 4.2.11 on 2024-08-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_rename_conditions_equipment_tools_responsiva_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_tools_responsiva',
            name='comments',
        ),
    ]
