# Generated by Django 4.2.11 on 2024-08-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_remove_equipment_tools_responsiva_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='comments',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Condiciones'),
        ),
    ]
