# Generated by Django 4.2.11 on 2024-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_remove_equipment_tools_responsiva_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='comments',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Condiciones'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='document_equipment',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Documento'),
        ),
    ]
