# Generated by Django 4.2.11 on 2024-09-06 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0011_equipment_tools_responsiva_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del equipo'),
        ),
        migrations.AlterField(
            model_name='equipment_tools_responsiva',
            name='comments',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Comentarios'),
        ),
    ]
