# Generated by Django 4.2.11 on 2024-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_equipment_tools_equipment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Ficha tecnica'),
        ),
        migrations.AlterField(
            model_name='equipment_tools_responsiva',
            name='document_equipment',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Documento'),
        ),
    ]
