# Generated by Django 4.2.11 on 2024-09-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_alter_equipment_tools_equipment_technical_sheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_tools',
            name='equipment_area',
        ),
        migrations.RemoveField(
            model_name='equipment_tools',
            name='equipment_responsible',
        ),
    ]
