# Generated by Django 4.2.11 on 2024-09-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0014_remove_equipment_tools_equipment_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools',
            name='equipment_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='equipment_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del equipo'),
        ),
    ]
