# Generated by Django 4.2.11 on 2024-09-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_equipment_tools_equipment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement_category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='equipement_category',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Corto'),
        ),
    ]
