# Generated by Django 4.2.11 on 2024-09-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0017_alter_equipment_tools_equipment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_brand',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='modules.equipement_category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_description',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_location',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_name',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='Nombre equipo'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Ficha tecnica'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_type',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True, verbose_name='tipo de equipo'),
        ),
    ]
