# Generated by Django 4.2.11 on 2024-09-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_alter_equipment_tools_equipment_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_tools_responsiva',
            name='document_equipment',
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='date_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de recibido'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='signature_almacen',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Firma de almacen'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='signature_responsible',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Firma del responsable'),
        ),
    ]
