# Generated by Django 4.2.11 on 2024-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_remove_equipment_tools_responsiva_document_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='status_modified',
            field=models.BooleanField(default=False, verbose_name='Estado modificado'),
        ),
    ]
