# Generated by Django 4.2.11 on 2024-09-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_equipment_tools_responsiva_status_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='return_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Cantidad devuelta'),
        ),
    ]
