# Generated by Django 4.2.11 on 2024-09-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0021_equipment_tools_responsiva_return_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_tools_responsiva',
            name='return_amount',
        ),
    ]
