# Generated by Django 4.2.11 on 2024-09-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0022_remove_equipment_tools_responsiva_return_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_tools',
            name='equipment_location',
        ),
    ]
