# Generated by Django 4.2.11 on 2024-09-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0024_equipmets_tools_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools',
            name='equipment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
    ]
