# Generated by Django 4.2.11 on 2024-09-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0025_equipment_tools_equipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.equipmets_tools_locations', verbose_name='Ubicación'),
        ),
    ]
