# Generated by Django 4.2.11 on 2024-09-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0026_alter_equipment_tools_equipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools_responsiva',
            name='signature_almacen',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools/signatures/', verbose_name='Firma de almacen'),
        ),
        migrations.AlterField(
            model_name='equipment_tools_responsiva',
            name='signature_responsible',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools/signatures/', verbose_name='Firma del responsable'),
        ),
    ]
