# Generated by Django 4.2.11 on 2024-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0027_alter_equipment_tools_responsiva_signature_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='equipment_tools_responsiva',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cantidad'),
        ),
    ]
