# Generated by Django 4.2.11 on 2024-10-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0028_alter_equipment_tools_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='equipment_tools_responsiva',
            name='comments',
            field=models.CharField(blank=True, default='Regular', max_length=300, null=True, verbose_name='Comentarios'),
        ),
    ]
