# Generated by Django 4.2.11 on 2024-10-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0029_alter_equipment_tools_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='Vehicle_Maintenance_Kilometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(default='current', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
