# Generated by Django 4.2.11 on 2024-10-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0030_equipment_tools_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
    ]
