# Generated by Django 4.2.11 on 2025-01-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0031_equipment_tools_responsiva_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure_category',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
    ]
