# Generated by Django 4.2.11 on 2025-03-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_area_code_alter_area_created_at'),
        ('modules', '0032_equipement_category_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersystem',
            name='qr_info_computer',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/info/'),
        ),

    ]
