# Generated by Django 4.2.11 on 2025-02-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0032_services_category_services_payments_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_access',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/access/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_info',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/info/'),
        ),
    ]
