# Generated by Django 4.2.11 on 2025-01-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0032_infrastructure_category_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure_category',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='infrastructure_category',
            name='short_name',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Nombre Corto'),
        ),
    ]
