# Generated by Django 4.2.11 on 2025-02-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_vehicle_qr_access_vehicle_qr_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Maintenance_Kilometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(default='current', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
