# Generated by Django 4.2.11 on 2025-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_services_category_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_category',
            name='name_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='services_category',
            name='short_name_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Corto'),
        ),
    ]
