# Generated by Django 4.2.11 on 2025-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_equipement_category_empresa_vehicle_driver_multas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_maintenance_kilometer',
            name='kilometer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
