# Generated by Django 4.2.11 on 2025-03-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_computersystem_qr_info_computer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computersystem',
            name='qr_info_computer',
        ),
    ]
