# Generated by Django 4.2.11 on 2025-02-14 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0033_vehicle_qr_access_vehicle_qr_info'),
    ]

    operations = [
    
        
    ]
