# Generated by Django 4.2.11 on 2025-03-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_area_code_alter_area_created_at'),
        ('modules', '0033_vehicle_qr_access_vehicle_qr_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle_audit',
            options={},
        ),
        migrations.RenameField(
            model_name='vehicle_audit',
            old_name='notes_exterior',
            new_name='checks',
        ),
        
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_antifreeze_level',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_exterior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_fuel_level',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_interior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_tires',
        ),
                migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_interior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_tires',
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='is_visible',
        ),
    ]
