# Generated by Django 4.2.11 on 2025-03-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_area_code_alter_area_created_at'),
        ('modules', '0033_equipement_category_empresa_vehicle_driver_multas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle_audit',
            options={},
        ),
        migrations.RenameField(
            model_name='vehicle_audit',
            old_name='notes_exterior',
            new_name='checks',
        ),
        
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_antifreeze_level',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_exterior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_fuel_level',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_interior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_tires',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_interior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_tires',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_maintenance',
            name='mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_maintenance_kilometer',
            name='kilometer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_responsive',
            name='final_mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_responsive',
            name='initial_mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
