# Generated by Django 4.2.11 on 2024-11-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_payments_services_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments_services',
            name='status_payment',
        ),
    ]
