# Generated by Django 4.2.11 on 2025-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0034_vehicle_maintenance_kilometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_responsive',
            name='status',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
