# Generated by Django 4.2.11 on 2025-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0034_vehicle_driver_multas_licences_driver'),
    ]

    operations = [
        
    ]
