# Generated by Django 4.2.11 on 2024-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0034_remove_payments_services_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_services',
            name='status_payment',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('upcoming', 'Próximo'), ('unpaid', 'No Pagado'), ('paid', 'Pagado')], default='pending', max_length=10, verbose_name='Estado de pago'),
        ),
    ]
