# Generated by Django 4.2.11 on 2025-03-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_area_code_alter_area_created_at'),
        ('modules', '0034_alter_vehicle_audit_options_and_more'),
    ]

    operations = [

        

    ]
