# Generated by Django 4.2.11 on 2025-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0034_remove_computersystem_qr_info_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersystem',
            name='qr_info_computer',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/info/'),
        ),
    ]
