# Generated by Django 4.2.11 on 2024-12-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0034_alter_services_category_name_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_plan', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('type_plan', models.CharField(choices=[('basic', 'Basico'), ('advanced', 'Avanzado'), ('premium', 'Premium')], default='pending', max_length=10, verbose_name='Tipo de plan')),
                ('status_payment_plan', models.BooleanField(default=False, verbose_name='Estado de pago')),
                ('time_quantity_plan', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad de Tiempo')),
                ('time_unit_plan', models.CharField(blank=True, choices=[('day', 'Día(s)'), ('month', 'Mes(es)'), ('year', 'Año(s)')], max_length=50, null=True, verbose_name='Unidad de Tiempo')),
                ('end_date_plan', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Costo\xa0total')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.module', verbose_name='Módulos')),
            ],
        ),
    ]
