# Generated by Django 4.2.11 on 2025-02-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0035_vehicle_driver_address_vehicle_driver_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_driver',
            old_name='serial_number',
            new_name='number_phone',
        ),
    ]
