# Generated by Django 4.2.11 on 2025-03-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0035_alter_vehicle_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_maintenance',
            name='mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_responsive',
            name='final_mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_responsive',
            name='initial_mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
