# Generated by Django 4.2.11 on 2025-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0035_computersystem_qr_info_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure_item',
            name='qr_info_infrastructure',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/info/'),
        ),
    ]
