# Generated by Django 4.2.11 on 2025-03-13 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0035_rename_notes_exterior_vehicle_audit_checks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_audit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
