# Generated by Django 4.2.11 on 2025-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0035_vehicle_responsive_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_responsive',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicle_maintenance',
            name='status',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
