# Generated by Django 4.2.11 on 2025-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0036_rename_serial_number_vehicle_driver_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_driver',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre completo'),
        ),
    ]
