# Generated by Django 4.2.11 on 2025-01-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0032_equipement_category_empresa'),
        ('modules', '0033_alter_infrastructure_category_name_and_more'),
        ('modules', '0036_plans'),
    ]

    operations = [
    ]
