# Generated by Django 4.2.11 on 2025-03-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0034_alter_vehicle_audit_options_and_more'),
        ('modules', '0036_infrastructure_item_qr_info_infrastructure'),
    ]

    operations = [
    ]
