# Generated by Django 4.2.11 on 2025-03-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0037_merge_20250324_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerperipheral',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.AddField(
            model_name='computersystem',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
