# Generated by Django 4.2.11 on 2025-02-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0037_vehicle_driver_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_driver',
            name='full_name',
        ),
    ]
