# Generated by Django 4.2.11 on 2025-03-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0038_computerperipheral_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersystem',
            name='adquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición'),
        ),
    ]
