# Generated by Django 4.2.11 on 2025-02-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0038_remove_vehicle_driver_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle', verbose_name='Vehiculo'),
        ),
    ]
