# Generated by Django 4.2.11 on 2025-02-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0039_multas_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('options', models.CharField(blank=True, choices=[('muy malo', 'Muy malo'), ('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno'), ('muy bueno', 'Muy bueno'), ('excelente', 'Excelente')], max_length=50, null=True, verbose_name='Opciones')),
            ],
        ),
    ]
