# Generated by Django 4.2.11 on 2025-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0039_computersystem_adquisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersystem',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador'),
        ),
    ]
