# Generated by Django 4.2.11 on 2025-02-26 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0040_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('muy malo', 'Muy malo'), ('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno'), ('muy bueno', 'Muy bueno'), ('excelente', 'Excelente')], max_length=20), blank=True, null=True, size=None),
        ),
    ]
