# Generated by Django 4.2.11 on 2025-02-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('modules', '0041_alter_checks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checks',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
