# Generated by Django 4.2.11 on 2025-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0041_equipment_tools_responsiva_email_responsiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_services',
            name='email_payment_unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
