# Generated by Django 4.2.11 on 2025-02-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0042_checks_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checks',
            name='options',
        ),
    ]
