# Generated by Django 4.2.11 on 2025-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0042_payments_services_email_payment_unpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='email_responsiva_aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='email_responsiva_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='email_responsiva_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='email_responsiva_next',
            field=models.BooleanField(default=False),
        ),
    ]
