# Generated by Django 4.2.11 on 2025-03-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0043_remove_checks_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_audit',
            old_name='check_antifreeze_level',
            new_name='checks',
        ),
        migrations.RenameField(
            model_name='vehicle_audit',
            old_name='general_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_exterior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_fuel_level',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_interior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='check_tires',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_exterior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_interior',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='notes_tires',
        ),
    ]
