# Generated by Django 4.2.11 on 2025-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0043_equipment_tools_responsiva_email_responsiva_aceptada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_tenencia',
            name='email_sin_tenencia',
            field=models.BooleanField(default=False),
        ),
    ]
