# Generated by Django 4.2.11 on 2025-03-03 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0044_rename_check_antifreeze_level_vehicle_audit_checks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle_audit',
            options={},
        ),
        migrations.RenameField(
            model_name='vehicle_audit',
            old_name='notes',
            new_name='general_notes',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='checks',
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VehicleAuditCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=50)),
                ('check_value', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='modules.vehicle_audit')),
            ],
        ),
    ]
