# Generated by Django 4.2.11 on 2025-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0044_vehicle_tenencia_email_sin_tenencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_tenencia',
            name='email_sin_tenencia',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_tenencia',
            field=models.BooleanField(default=False),
        ),
    ]
