# Generated by Django 4.2.11 on 2025-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0045_alter_vehicle_audit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='vehicle_audit',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='checks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VehicleAuditCheck',
        ),
    ]
