# Generated by Django 4.2.11 on 2025-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0045_remove_vehicle_tenencia_email_sin_tenencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_refrendo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_responsive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_sin_verificacion',
            field=models.BooleanField(default=False),
        ),
    ]
