# Generated by Django 4.2.11 on 2025-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0046_vehicle_email_sin_audit_vehicle_email_sin_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='email_verificacion_s1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='email_verificacion_s2',
            field=models.BooleanField(default=False),
        ),
    ]
