# Generated by Django 4.2.11 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0047_vehicle_email_verificacion_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_gasoline',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/access/'),
        ),
        migrations.AddField(
            model_name='vehicle_maintenance',
            name='email_maintenance_proximo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_maintenance',
            name='email_maintenance_recordatorio',
            field=models.BooleanField(default=False),
        ),
    ]
