# Generated by Django 4.2.11 on 2025-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0048_vehicle_qr_gasoline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='qr_gasoline',
            new_name='qr_fuel',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type_vehicle',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Combustible'),
        ),
    ]
