# Generated by Django 4.2.11 on 2025-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0049_rename_qr_gasoline_vehicle_qr_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerperipheral',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='computersystem',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='software_identifier',
            field=models.CharField(help_text='Identificador del software proporcionado por el proveedor', max_length=255, verbose_name='Identificador del Software'),
        ),
    ]
