# Generated by Django 4.2.11 on 2025-04-28 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_email_company'),
        ('modules', '0050_alter_computerperipheral_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure_item',
            name='time_quantity',
        ),
        migrations.RemoveField(
            model_name='infrastructure_item',
            name='time_unit',
        ),
        migrations.AddField(
            model_name='infrastructure_item',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='infrastructure_item',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='infrastructure_item',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Ficha tecnica'),
        ),
        migrations.CreateModel(
            name='Items_locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='¿Está activa la ubicación?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.AddField(
            model_name='infrastructure_item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.items_locations', verbose_name='Ubicación'),
        ),
    ]
