# Generated by Django 4.2.11 on 2025-04-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0050_alter_computerperipheral_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_verificacion',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PROXIMO', 'Próximo')], default='PENDIENTE', max_length=10),
        ),
    ]
