# Generated by Django 4.2.11 on 2025-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0051_vehicle_verificacion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_insurance',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PROXIMO', 'Próximo')], default='PAGADO', max_length=10),
        ),
    ]
