# Generated by Django 4.2.11 on 2025-04-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0051_remove_infrastructure_item_time_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure_item',
            name='location',
        ),
        migrations.DeleteModel(
            name='Items_locations',
        ),
    ]
