# Generated by Django 4.2.11 on 2025-04-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_company_email_company'),
        ('modules', '0052_remove_infrastructure_item_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='¿Está activa la ubicación?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.AddField(
            model_name='infrastructure_item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.items_locations', verbose_name='Ubicación'),
        ),
    ]
