# Generated by Django 4.2.11 on 2025-05-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0052_vehicle_insurance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_insurance',
            name='status',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PROXIMO', 'Próximo a vencer'), ('VENCIDO', 'Vencido'), ('PENDIENTE', 'Pendiente de pago'), ('HISTORICO', 'Histórico')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vehicle_insurance',
            index=models.Index(fields=['status'], name='modules_veh_status_8ec07f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle_insurance',
            index=models.Index(fields=['end_date'], name='modules_veh_end_dat_47a1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle_insurance',
            index=models.Index(fields=['vehicle', 'policy_number'], name='modules_veh_vehicle_6a1aff_idx'),
        ),
    ]
