# Generated by Django 4.2.11 on 2025-05-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0053_alter_vehicle_insurance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_insurance',
            name='status',
            field=models.CharField(choices=[('PAGADO', 'PAGADO'), ('PROXIMO', 'PROXIMO'), ('VENCIDO', 'VENCIDO'), ('PENDIENTE', 'PENDIENTE'), ('HISTORICO', 'HISTORICO')], default='PENDIENTE', max_length=20),
        ),
    ]
