# Generated by Django 4.2.11 on 2025-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0053_items_locations_infrastructure_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure_item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='Factura'),
        ),
    ]
