# Generated by Django 4.2.11 on 2025-04-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_company_email_company'),
        ('modules', '0055_infrastructureitemdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('record_type', models.CharField(blank=True, max_length=32, null=True)),
                ('checked', models.CharField(blank=True, default='Regular', max_length=20, null=True, verbose_name='Check')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('general_notes', models.TextField(blank=True, max_length=255, null=True)),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.infrastructureitemdetail', verbose_name='Item')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
            ],
        ),
        migrations.DeleteModel(
            name='Infrastructure_Review',
        ),
    ]
