# Generated by Django 4.2.11 on 2025-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0057_maintenanceaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure_item',
            name='qr_info_infrastructure',
        ),
        migrations.AddField(
            model_name='infrastructureitemdetail',
            name='qr_info_infrastructure',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/info/'),
        ),
    ]
