# Generated by Django 4.2.11 on 2025-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0058_remove_infrastructure_item_qr_info_infrastructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure_maintenance',
            name='actions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
