# Generated by Django 4.2.11 on 2025-05-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0059_infrastructure_maintenance_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure_maintenance',
            name='checked',
        ),
    ]
