# Generated by Django 4.2.11 on 2025-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0060_remove_infrastructure_maintenance_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure_maintenance',
            name='record_type',
        ),
        migrations.AddField(
            model_name='infrastructure_maintenance',
            name='status',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
