# Generated by Django 4.2.11 on 2025-06-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0054_alter_vehicle_insurance_status'),
        ('modules', '0062_infrastructure_maintenance_comprobante'),
    ]

    operations = [
    ]
