# Generated by Django 4.2.11 on 2025-06-12 17:05
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0054_alter_vehicle_insurance_status'),
        ('modules', '0062_infrastructure_maintenance_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='apply_tenencia',
            field=models.BooleanField(default=False, verbose_name='Aplica tenencia'),
        ),
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=255)),
                ('type_plate', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('entidad_emisora', models.CharField(blank=True, max_length=64, null=True)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('status', models.CharField(default='blank', max_length=255)),
                ('document_placa', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de placa')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('number', models.CharField(max_length=255)),
                ('status', models.CharField(default='blank', max_length=255)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('document_factura', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de factura')),
                ('name_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Hologram_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hologram', models.DateField()),
                ('document_hologram', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de holograma')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contract', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_contract', models.DateField()),
                ('fecha_finiquito', models.DateField()),
                ('status_modified', models.BooleanField(default=False, verbose_name='Estado modificado')),
                ('document_contract', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de contrato')),
                ('document_letter', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='carta de finiquito')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Contrato cancelado')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Carnet_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_carnet', models.DateField()),
                ('document_carnet', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de carnet')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=50)),
                ('type_card', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='blank', max_length=255)),
                ('document_card', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de tarjeta')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('name_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),

    ]
