# Generated by Django 4.2.11 on 2025-05-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0063_merge_20250523_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='placas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10)),
                ('type_plate', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('entidad_emisora', models.CharField(blank=True, max_length=64, null=True)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
