# Generated by Django 4.2.11 on 2025-06-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0063_merge_20250612_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='apply_tenencia',
            field=models.BooleanField(default=False, verbose_name='Aplica tenencia'),
        ),
    ]
