# Generated by Django 4.2.11 on 2025-07-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0064_vehicle_apply_tenencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('stripedID', models.CharField(blank=True, max_length=44)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('tagPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card_vehicle',
            name='number_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='multas',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='type_plan',
            field=models.CharField(choices=[('basic', 'Basico'), ('advanced', 'Avanzado'), ('premium', 'Premium'), ('elite', 'Elite'), ('esential', 'Esential')], default='pending', max_length=10, verbose_name='Tipo de plan'),
        ),
    ]
