# Generated by Django 4.2.11 on 2025-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0064_placas'),
    ]

    operations = [
        migrations.AddField(
            model_name='placas',
            name='document_placa',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='diocumento de placa'),
        ),
        migrations.AddField(
            model_name='placas',
            name='status',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
