# Generated by Django 4.2.11 on 2025-07-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notification_system_status'),
        ('modules', '0065_stripeproducts_alter_card_vehicle_number_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_insurance',
            name='status',
            field=models.CharField(choices=[('PAGADO', 'PAGADO'), ('PROXIMO', 'PROXIMO'), ('VENCIDO', 'VENCIDO'), ('PENDIENTE', 'PENDIENTE'), ('HISTORICO', 'HISTORICO')], default='PROXIMO', max_length=20),
        ),
        migrations.CreateModel(
            name='Services_locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='¿Está activa la ubicación?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.services_locations', verbose_name='Ubicación'),
        ),
    ]
