# Generated by Django 4.2.11 on 2025-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0065_placas_document_placa_placas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placas',
            name='document_placa',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de placa'),
        ),
    ]
