# Generated by Django 4.2.11 on 2025-08-04 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0066_alter_vehicle_insurance_status_services_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='location',
        ),
        migrations.AddField(
            model_name='checks',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Imagen del chek'),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Services_locations',
        ),
    ]
