# Generated by Django 4.2.11 on 2025-05-30 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0066_alter_placas_document_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(default='blank', max_length=255)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('document_factura', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de factura')),
                ('name_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
