# Generated by Django 4.2.11 on 2025-08-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0067_remove_services_location_checks_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='apply_tenencia',
        ),
    ]
