# Generated by Django 4.2.11 on 2025-06-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0067_facturas_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=20)),
                ('type_card', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='blank', max_length=255)),
                ('document_card', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de tarjeta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
