# Generated by Django 4.2.11 on 2025-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0068_remove_vehicle_apply_tenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='apply_tenencia',
            field=models.BooleanField(default=False, verbose_name='Aplica tenencia'),
        ),
    ]
