# Generated by Django 4.2.11 on 2025-06-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0068_card_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_vehicle',
            name='name_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del conductor'),
        ),
    ]
