# Generated by Django 4.2.11 on 2025-08-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0069_vehicle_apply_tenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_audit',
            name='calification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
