# Generated by Django 4.2.11 on 2025-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0069_card_vehicle_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_vehicle',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
