# Generated by Django 4.2.11 on 2025-06-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0070_card_vehicle_fecha_vencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas_vehicle',
            old_name='fecha_emision',
            new_name='fecha_vencimiento',
        ),
    ]
