# Generated by Django 4.2.11 on 2025-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0070_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_audit',
            name='calification',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
