# Generated by Django 4.2.11 on 2025-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0071_alter_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_tenencia',
            name='email_sin_tenencia',
            field=models.BooleanField(default=False),
        ),
    ]
