# Generated by Django 4.2.11 on 2025-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0071_alter_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_maintenance',
            name='status',
            field=models.CharField(default='NUEVO', max_length=255),
        ),
    ]
