# Generated by Django 4.2.11 on 2025-06-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0071_rename_fecha_emision_facturas_vehicle_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contract', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_contract', models.DateField()),
                ('fecha_finiquito', models.DateField()),
                ('status_modified', models.BooleanField(default=False, verbose_name='Estado modificado')),
                ('document_contract', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de tarjeta')),
                ('document_letter', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de tarjeta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
