# Generated by Django 4.2.11 on 2025-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0071_alter_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_audit',
            name='calification',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
