# Generated by Django 4.2.11 on 2025-08-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0072_vehicle_tenencia_email_sin_tenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
