# Generated by Django 4.2.11 on 2025-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0072_contract_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_vehicle',
            name='document_contract',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de contrato'),
        ),
        migrations.AlterField(
            model_name='contract_vehicle',
            name='document_letter',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='carta de finiquito'),
        ),
    ]
