# Generated by Django 4.2.11 on 2025-08-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0072_alter_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_evaluated_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_evaluated_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_tenencia',
            name='email_sin_tenencia',
            field=models.BooleanField(default=False),
        ),
        
    ]
