# Generated by Django 4.2.11 on 2025-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0073_vehicle_audit_email_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_evaluated_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_audit',
            name='email_evaluated_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
