# Generated by Django 4.2.11 on 2025-06-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0073_alter_contract_vehicle_document_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_vehicle',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Contrato cancelado'),
        ),
    ]
