# Generated by Django 4.2.11 on 2025-08-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0073_vehicle_audit_email_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_verificacion',
            name='email_verificacion_days',
            field=models.BooleanField(default=False),
        )
    ]
