# Generated by Django 4.2.11 on 2025-08-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0074_vehicle_verificacion_email_verificacion_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_verificacion',
            name='email_verificacion_vencida',
            field=models.BooleanField(default=False),
        ),
    ]
