# Generated by Django 4.2.11 on 2025-06-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0074_contract_vehicle_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter_Facturas_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('document_letter_factura', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de factura')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
