# Generated by Django 4.2.11 on 2025-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0075_vehicle_verificacion_email_verificacion_vencida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_tires',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
