# Generated by Django 4.2.11 on 2025-06-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0075_letter_facturas_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter_facturas_vehicle',
            name='comments',
        ),
    ]
