# Generated by Django 4.2.11 on 2025-06-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0076_remove_letter_facturas_vehicle_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hologram_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hologram', models.DateField()),
                ('document_hologram', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de holograma')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
