# Generated by Django 4.2.11 on 2025-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0076_vehicle_car_tires'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_audit',
            name='commitment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
