# Generated by Django 4.2.11 on 2025-08-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0077_vehicle_audit_commitment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAuditEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='audit_evidences/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='modules.vehicle_audit')),
            ],
        ),
    ]
