# Generated by Django 4.2.11 on 2025-06-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0077_hologram_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_carnet', models.DateField()),
                ('document_carnet', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de carnet')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle')),
            ],
        ),
    ]
