# Generated by Django 4.2.11 on 2025-08-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0078_vehicleauditevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAuditCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='audit_corrections/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='modules.vehicle_audit')),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleAuditEvidence',
        ),
    ]
