# Generated by Django 4.2.11 on 2025-06-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0078_service_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Vehicle',
            new_name='Carnet_Vehicle',
        ),
    ]
