# Generated by Django 4.2.11 on 2025-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0079_vehicleauditcorrection_delete_vehicleauditevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleauditcorrection',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
