# Generated by Django 4.2.11 on 2025-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0079_rename_service_vehicle_carnet_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_vehicle',
            name='number_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facturas_vehicle',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='multas',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='placas',
            name='plate',
            field=models.CharField(max_length=50),
        ),
    ]
