# Generated by Django 4.2.11 on 2025-09-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0080_alter_vehicleauditcorrection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='apply_tenencia',
        ),
    ]
