# Generated by Django 4.2.11 on 2025-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0081_remove_vehicle_apply_tenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_refrendo',
            name='email_sin_comprobante',
            field=models.BooleanField(default=False),
        ),
    ]
