# Generated by Django 4.2.11 on 2025-09-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0082_vehicle_refrendo_email_sin_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_verificacion',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PROXIMO', 'Próximo'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10),
        ),
    ]
