# Generated by Django 4.2.11 on 2026-04-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0083_alter_vehicle_verificacion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_audit',
            name='calification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
