# Generated by Django 4.2.11 on 2026-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0084_alter_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_audit',
            name='calification',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
