# Generated by Django 4.2.11 on 2026-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0085_alter_vehicle_audit_calification'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersystem',
            name='document_factura',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de factura'),
        ),
    ]
