# Generated by Django 4.2.11 on 2026-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0086_computersystem_document_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerequipment_maintenance',
            name='document',
        ),
        migrations.AddField(
            model_name='computerequipment_maintenance',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de matenimiento', null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='computersystem',
            name='intervaL_maintenance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='payments_services',
            name='proof_payment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='docs/', verbose_name='Comprobante de pago'),
        ),
    ]
