# Generated by Django 4.2.11 on 2026-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0086_computersystem_document_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments_services',
            name='proof_payment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='docs/', verbose_name='Comprobante de pago'),
        ),
    ]
