# Generated by Django 4.2.11 on 2026-06-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0087_remove_computerequipment_maintenance_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computersystem',
            name='intervaL_maintenance',
        ),
    ]
