# Generated by Django 4.2.11 on 2026-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0087_alter_payments_services_proof_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerequipment_maintenance',
            name='document',
        ),
        migrations.AddField(
            model_name='computerequipment_maintenance',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de matenimiento', null=True, upload_to='docs/'),
        ),
    ]
