# Generated by Django 4.2.11 on 2026-06-23 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        ('modules', '0087_remove_computerequipment_maintenance_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeClient', models.CharField(max_length=100, null='True', verbose_name='Stripe_cliente')),
                ('StripeProductss', models.CharField(max_length=100, null='True', verbose_name='Stripe_producto')),
                ('stripeSubcription', models.CharField(max_length=100, null='True', verbose_name='Stripe_subscripcion')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('q_modules', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad de modulos')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.module', verbose_name='titulo_modulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable temporal')),
            ],
        ),
        migrations.AddField(
            model_name='plans',
            name='planHeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.planheader', verbose_name='planheader'),
        ),
    ]
