# Generated by Django 4.2.11 on 2026-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0088_remove_computersystem_interval_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersystem',
            name='intervaL_maintenance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia de mantenimiento'),
        ),
    ]
