# Generated by Django 4.2.11 on 2026-06-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0088_planheader_plans_planheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planheader',
            name='created_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
