# Generated by Django 4.2.11 on 2026-05-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0088_computerequipment_maintenance_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerequipment_maintenance',
            name='document',
        ),
    ]
