# Generated by Django 4.2.11 on 2026-06-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0089_alter_planheader_created_at'),
        ('modules', '0089_alter_planheader_created_at_alter_planheader_title'),
    ]

    operations = [
    ]
