# Generated by Django 4.2.11 on 2026-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0090_merge_20260623_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerEquipment_Maintenance',
        ),
    ]
