# Generated by Django 4.2.11 on 2026-07-09 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0091_delete_computerequipment_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerEquipment_Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(blank=True, help_text='Usuario o Proveedor', max_length=100, null=True, verbose_name='¿Quién lo hizo?')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de mantenimiento')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Acciones')),
                ('document', models.FileField(blank=True, null=True, upload_to='doc/maintenance/', verbose_name='Documento')),
                ('is_checked', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computerSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.computersystem', verbose_name='Equipo')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider', verbose_name='Proveedor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Equipo de Computo',
                'verbose_name_plural': 'Mantenimiento de Equipos de Computo',
            },
        ),
    ]
