# Generated by Django 4.2.11 on 2026-07-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0092_computerequipment_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerperipheral',
            name='factura_document',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='documento de factura'),
        ),
    ]
