# Generated by Django 4.2.11 on 2026-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0093_computerperipheral_factura_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='document_factura_vehicle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
