# Generated by Django 4.2.11 on 2026-07-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0094_vehicle_document_factura_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_tools',
            name='document_factura_equipment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
