# Generated by Django 4.2.11 on 2026-07-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0095_equipment_tools_document_factura_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='document_factura_equipment',
            field=models.FileField(blank=True, null=True, upload_to='docs/Equipments_tools', verbose_name='factura'),
        ),
    ]
