# Generated by Django 4.2.11 on 2026-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0096_alter_equipment_tools_document_factura_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='document_factura_vehicle',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
