# Generated by Django 4.2.11 on 2026-07-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0097_alter_vehicle_document_factura_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_tools',
            name='document_factura_equipment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='docs/Equipments_tools', verbose_name='factura'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='equipment_technical_sheet',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='docs/Equipments_tools', verbose_name='Ficha tecnica'),
        ),
    ]
