# Generated by Django 4.2.11 on 2026-07-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0099_infraestructure_responsiva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraestructure_responsiva',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Responsiva de Infraestructura', 'verbose_name_plural': 'Responsivas de Infraestructura'},
        ),
    ]
