# Generated by Django 4.2.11 on 2026-07-27 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0100_alter_infraestructure_responsiva_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles_Responsivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True, null=True, verbose_name='Items')),
                ('record', models.TextField(blank=True, null=True, verbose_name='Historial')),
                ('responsibility_vehicle_pdf', models.FileField(blank=True, null=True, upload_to='doc/infraestructure/', verbose_name='Responsiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('area_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Área del responsable')),
                ('responsible_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Responsiva de Vehiculo',
                'verbose_name_plural': 'Responsivas de Vehiculos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
