# Generated by Django 4.2.11 on 2026-08-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0089_computersystem_interval_maintenance'),
        ('modules', '0101_vehicles_responsivas'),
    ]

    operations = [
    ]
