# Generated by Django 4.2.11 on 2026-08-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0101_vehicles_responsivas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='document_factura_vehicle',
        ),
    ]
