# Generated by Django 4.2.11 on 2026-08-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0102_remove_vehicle_document_factura_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas_vehicle',
            name='fecha_vencimiento',
        ),
    ]
