# Generated by Django 4.2.11 on 2026-08-06 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        ('modules', '0103_remove_facturas_vehicle_fecha_vencimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles_Responsivas',
            new_name='Vehicles_Responsivas_pdf',
        ),
    ]
