# Generated by Django 4.2.11 on 2026-08-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0104_rename_vehicles_responsivas_vehicles_responsivas_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles_responsivas_pdf',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Responsiva de Vehiculo', 'verbose_name_plural': 'Responsivas_pdf de Vehiculos'},
        ),
    ]
