# Generated by Django 4.2.11 on 2026-08-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0105_alter_vehicles_responsivas_pdf_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles_responsivas_pdf',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle', verbose_name='Vehículo'),
        ),
    ]
