# Generated by Django 4.2.11 on 2026-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0106_vehicles_responsivas_pdf_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_maintenance',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
