# Generated by Django 4.2.11 on 2026-08-12 19:05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0101_vehicles_responsivas'),
        ('modules', '0089_computersystem_interval_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_maintenance',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]