# Generated by Django 4.2.11 on 2026-09-24 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0107_vehicle_maintenance_is_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments_Tools_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('VENDIDO', 'Vendido'), ('OBSOLETO', 'Obsoleto'), ('PERDIDO', 'Perdido'), ('BAJA', 'Baja'), ('ROBADO', 'Robado')], max_length=20, null=True, verbose_name='Motivo de baja')),
                ('deactivation_description', models.TextField(blank=True, null=True, verbose_name='Descripción de la baja')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('state', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=64, verbose_name='Estado del equipó')),
                ('evidence1_image', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('evidence2_image', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tool_details', to='modules.equipmets_tools_locations', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Detalle de equipo o herramienta',
                'verbose_name_plural': 'Detalles de equipo o herramienta',
            },
        ),

    ]
