# Generated by Django 4.2.11 on 2026-09-24 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0107_vehicle_maintenance_is_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Responsiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_equipment_tool', models.CharField(blank=True, choices=[('ASIGNADO', 'Asignado'), ('REGRESADO', 'Regresado'), ('BAJA', 'Baja'), ('NO DEVUELTO', 'No devuelto'), ('DAÑADO', 'Dañado')], max_length=20, null=True, verbose_name='Motivo de baja')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments_Tools_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('VENDIDO', 'Vendido'), ('OBSOLETO', 'Obsoleto'), ('PERDIDO', 'Perdido'), ('BAJA', 'Baja'), ('ROBADO', 'Robado')], max_length=20, null=True, verbose_name='Motivo de baja')),
                ('deactivation_description', models.TextField(blank=True, null=True, verbose_name='Descripción de la baja')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('state', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=64, verbose_name='Estado del equipó')),
                ('evidence1_image', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('evidence2_image', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tool_details', to='modules.equipmets_tools_locations', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Detalle de equipo o herramienta',
                'verbose_name_plural': 'Detalles de equipo o herramienta',
            },
        ),
        migrations.CreateModel(
            name='Vehicles_Responsivas_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True, null=True, verbose_name='Items')),
                ('record', models.TextField(blank=True, null=True, verbose_name='Historial')),
                ('responsibility_vehicle_pdf', models.FileField(blank=True, null=True, upload_to='doc/infraestructure/', verbose_name='Responsiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('area_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Área del responsable')),
                ('responsible_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Responsiva de Vehiculo',
                'verbose_name_plural': 'Responsivas_pdf de Vehiculos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='computerequipment_maintenance',
            name='document',
        ),
        migrations.RemoveField(
            model_name='facturas_vehicle',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='document_factura_vehicle',
        ),
        migrations.AddField(
            model_name='computerequipment_maintenance',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de matenimiento', null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de equipo o herramienta'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='has_serial_number',
            field=models.BooleanField(default=False, verbose_name='Cuenta con número de serie'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='email_responsiva_cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='reason_date_change',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo por el cambio de fecha'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='status_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tools_responsiva_status_modified', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de almacén'),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de equipos'),
        ),
        migrations.DeleteModel(
            name='Vehicles_Responsivas',
        ),
        migrations.AddField(
            model_name='vehicles_responsivas_pdf',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='equipment_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='modules.equipment_tools'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable temporal'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='responsiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_details', to='modules.equipment_tools_responsiva', verbose_name='Responsiva'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='user_activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tools_activations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la activación'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='user_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tools_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la modificación'),
        ),
        migrations.AddField(
            model_name='detail_responsiva',
            name='details_equipment_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_equipment', to='modules.equipments_tools_detail', verbose_name='detalle del equipo'),
        ),
        migrations.AddField(
            model_name='detail_responsiva',
            name='responsiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_responsiva', to='modules.equipment_tools_responsiva', verbose_name='Responsiva'),
        ),
    ]
