# Generated by Django 4.2.11 on 2026-09-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_company_accept_terms_company_accept_terms_date'),
        ('modules', '0108_detail_responsiva_equipments_tools_detail_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='equipments_tools_detail',
                    name='modification_date',
                    field=models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Fecha de activacion'
                    ),
                ),
            ],
            state_operations=[
        migrations.CreateModel(
            name='Detail_Responsiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_equipment_tool', models.CharField(blank=True, choices=[('ASIGNADO', 'Asignado'), ('REGRESADO', 'Regresado'), ('BAJA', 'Baja'), ('NO DEVUELTO', 'No devuelto'), ('DAÑADO', 'Dañado')], max_length=20, null=True, verbose_name='Motivo de baja')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Responsivas_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True, null=True, verbose_name='Items')),
                ('record', models.TextField(blank=True, null=True, verbose_name='Historial')),
                ('responsibility_vehicle_pdf', models.FileField(blank=True, null=True, upload_to='doc/infraestructure/', verbose_name='Responsiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('area_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Área del responsable')),
                ('responsible_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Responsiva de Vehiculo',
                'verbose_name_plural': 'Responsivas_pdf de Vehiculos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='computerequipment_maintenance',
            name='document',
        ),
        migrations.RemoveField(
            model_name='facturas_vehicle',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='document_factura_vehicle',
        ),
        migrations.AddField(
            model_name='computerequipment_maintenance',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de matenimiento', null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de equipo o herramienta'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='has_serial_number',
            field=models.BooleanField(default=False, verbose_name='Cuenta con número de serie'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='equipment_tools',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='email_responsiva_cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='reason_date_change',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo por el cambio de fecha'),
        ),
        migrations.AddField(
            model_name='equipment_tools_responsiva',
            name='status_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tools_responsiva_status_modified', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de almacén'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='equipment_tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='modules.equipment_tools'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable temporal'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='responsiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_details', to='modules.equipment_tools_responsiva', verbose_name='Responsiva'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='user_activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tools_activations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la activación'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='user_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_tools_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la modificación'),
        ),
        migrations.AddField(
            model_name='equipments_tools_detail',
            name='modification_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Fecha de activacion'
            ),
        ),
        migrations.AlterField(
            model_name='equipment_tools',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de equipos'),
        ),
        migrations.DeleteModel(
            name='Vehicles_Responsivas',
        ),
        migrations.AddField(
            model_name='vehicles_responsivas_pdf',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='detail_responsiva',
            name='details_equipment_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_equipment', to='modules.equipments_tools_detail', verbose_name='detalle del equipo'),
        ),
        migrations.AddField(
            model_name='detail_responsiva',
            name='responsiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_responsiva', to='modules.equipment_tools_responsiva', verbose_name='Responsiva'),
        ),
            ],
        ),
    ]
